version: "1"

services:
  # ----------------- API Gateway (Public Web Service) -----------------
  - type: web
    name: api-gateway
    plan: free
    runtime: docker
    dockerfilePath: ./api-gateway/Dockerfile
    buildCommand: "pip install grpcio==1.60.0 grpcio-tools==1.60.0 protobuf==4.25.3"
    healthCheckPath: /healthz # The gateway still uses a simple HTTP health check.
    envVars:
      - key: PORT
        value: 10000
      # --- KEY CHANGE ---
      # We now use the public URLs provided by Render. Render automatically
      # handles TLS, so gRPC connections will be secure over port 443.
      - key: GLOSSARY_SERVICE_ADDR
        value: glossary-service.onrender.com:443
      - key: GRAPH_SERVICE_ADDR
        value: graph-service.onrender.com:443
      - key: PYTHONUNBUFFERED
        value: 1

  # ----------------- Glossary Service (Public gRPC Service) -----------------
  - type: web
    name: glossary-service
    plan: free
    runtime: docker
    dockerfilePath: ./glossary-service/Dockerfile
    # --- KEY CHANGE ---
    # The build command now installs the required health-checking library.
    buildCommand: "pip install grpcio==1.60.0 grpcio-tools==1.60.0 protobuf==4.25.3 grpcio-health-checking==1.60.0"
    # --- KEY CHANGE ---
    # The 'healthCheckPath' is removed. Render will automatically detect and
    # use the standard gRPC health check that we implemented.
    envVars:
      # This port is now used for the main gRPC server and its health check.
      - key: PORT
        value: 10000
      - key: DATABASE_PATH
        value: /tmp/glossary.db
      - key: PYTHONUNBUFFERED
        value: 1

  # ----------------- Graph Service (Public gRPC Service) -----------------
  - type: web
    name: graph-service
    plan: free
    runtime: docker
    dockerfilePath: ./graph-service/Dockerfile
    # --- KEY CHANGE ---
    # The build command now installs the required health-checking library.
    buildCommand: "pip install grpcio==1.60.0 grpcio-tools==1.60.0 protobuf==4.25.3 grpcio-health-checking==1.60.0"
    # --- KEY CHANGE ---
    # The 'healthCheckPath' is removed. Render will automatically use the gRPC health check.
    envVars:
      # This port is now used for the main gRPC server and its health check.
      - key: PORT
        value: 10000
      - key: DATABASE_PATH
        value: /tmp/graph.db
      - key: PYTHONUNBUFFERED
        value: 1