# This is the name of the workflow that will appear in the "Actions" tab of your GitHub repository.
name: CI Pipeline

# This section defines when the workflow will run.
on:
  # Run on pushes to the "main" branch.
  push:
    branches: [ "main" ]
  # Also run on pull requests targeting the "main" branch.
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # This job is named "build-and-lint".
  build-and-lint:
    # The type of runner that the job will run on. We use the latest version of Ubuntu.
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
      # Step 1: Checks out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Sets up the Python version we want to use.
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Step 3: Installs the necessary Python packages.
      - name: Install Dependencies and Linter
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          # Install the requirements for each service to verify they are valid.
          pip install -r api-gateway/requirements.txt
          pip install -r glossary-service/requirements.txt
          pip install -r graph-service/requirements.txt

      # Step 4: Runs the linter to check for code quality.
      - name: Lint with flake8
        run: |
          # Run flake8. --count shows total number of errors.
          # --show-source shows the problematic code. --statistics shows breakdown.
          flake8 . --count --show-source --statistics